# Generated by Django 5.1.4 on 2025-03-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_student_end_date_student_overall_listening_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="slug",
            field=models.SlugField(blank=True, max_length=60, unique=True),
        ),
    ]
